### ISSUE TITLE
an issue in the code  'ndt_registration.py /'

### ISSUE THREAD

**Issue by zhchyang2004** [hgupta01/ndt_map#1]
Hi, 

In Line 54,  should the code be amended as  follows? 
cov = R@cM[i]@R.T + cF[nbrs[i]]
cM[i] is not relevent to the expression on row vector or column vector in Line 46. 

Thanks!

**Comment by hgupta01** [comment]
Hi, 

The code/equations are correct. There are still improvements I have to make for the registration function to be more user friendly and understandable. 

for example: mM= mean of ndt cells of moving map
                     cM= covariance of ndt cells of moving map
Line 46: transform the mean of ndt cell of moving map (R@mean+t)
Line 54: transform the covariance of ndt cell of moving map (R.T@cov@R) + cov of fixed map

I hope this may have cleared your doubt a bit. you can check the cost function for NDT D2D cost function in ![paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.817.5962&rep=rep1&type=pdf) at equation 18.

**Comment by hgupta01** [comment]
i'm closing this issue as of now.
